routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*
 * ATTENTION à partir de Laravel 8.0, il y a un changement dans le routing qui peut faire que les views ne
 * fonctionnent plus correctement lors de l'appel de "action"
 * voir https://laravel.com/docs/8.x/upgrade#routing
 * Par exemple, cette ligne dans layout.blade.php ne fonctionnera pas si le namespace n'est pas rétablie
 * <a href="{!! action('ProprietairesController@index') !!}">
 */
Route::resource('proprietaires', 'ProprietairesController');
Route::resource('animaux', 'AnimauxController');

app/Models/Proprietaire.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Proprietaire extends Model
{
    protected $guarded = array('id');

    public function animaux() {
        //Exemple de nom de table et de relatedPivotKey ne respectant pas la convention
        return $this->belongsToMany('App\Models\Animal','animaux_proprietaires',null,'animal_id');
    }
}

app/Http/Controllers/ProprietairesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProprietaire;
use Illuminate\Http\Request;

use App\Models\Proprietaire;
use App\Models\Animal;

class ProprietairesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $proprietaires = Proprietaire::all();
        return view('proprietaire.index', compact('proprietaires'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $animaux = Animal::pluck('nom', 'id');

        return view('proprietaire.create', compact('animaux'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    //Exemple d'une route protégée à l'aide d'un request
    public function store(StoreProprietaire $request)
    {
        $p = new Proprietaire();
        $p->nom = $request->nom;
        $p->telephone = $request->telephone;
        $p->save();
        $p->animaux()->sync($request->animaux_id);

        return redirect('proprietaires');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $proprietaire = Proprietaire::find($id);//TODO ajouter une validation
        $animaux = $proprietaire->animaux()->pluck('nom', 'id');
        return view('proprietaire.show', compact('proprietaire', 'animaux'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $proprietaire = Proprietaire::find($id); //TODO ajouter une validation
        $animaux = Animal::pluck('nom', 'id');
        return view('proprietaire.edit', compact('proprietaire','animaux'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreProprietaire $request, $id)
    {
        $p = Proprietaire::find($id);//TODO ajouter une validation
        $p->nom = $request->nom;
        $p->telephone = $request->telephone;
        $p->save();
        $p->animaux()->sync($request->animaux_id);
        return redirect('proprietaires');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $p = Proprietaire::find($id);//TODO ajouter une validation
        $p->delete();

        return redirect('proprietaires');
    }
}

resources/views/proprietaire/create.blade.php
@extends('layout')
@section('content')

    <section class="header section-padding">
        <div class="container">
            <div class="header-text">
                <h1>Création d'un propriétaire</h1>
            </div>
        </div>
    </section>

    <div class="container">
        <section class="section-padding">
            <div class="jumbotron text-left">
                {!! Form::open(['url'=> 'proprietaires', 'class' => 'form-horizontal', 'role'=>'form']) !!}
                @include('proprietaire.editForm')
                <div class="form-group">
                    {!! Form::submit('Créer', ['class' => 'btn btn-primary'])!!}
                </div>
                {!! Form::close() !!}
            </div>
        </section>
    </div>
@stop

resources/views/proprietaire/edit.blade.php
@extends('layout')
@section('content')

    <section class="header section-padding">
        <div class="container">
            <div class="header-text">
                <h1>Édition d'un proprietaire</h1>
            </div>
        </div>
    </section>

    <div class="container">
        <section class="section-padding">
            <div class="jumbotron text-left">
                {!! Form::open(['action'=> ['ProprietairesController@update', $proprietaire->id], 'method' => 'PUT', 'class' => 'form-horizontal', 'role'=>'form']) !!}
                @include('proprietaire.editForm')
                <div class="form-group">
                    {!! Form::submit('Sauvegarder', ['class' => 'btn btn-primary']) !!}
                </div>
                {!! Form::close() !!}
            </div>
        </section>
    </div>
@stop

resources/views/proprietaire/editForm.blade.php
<?php
use App\Models\Proprietaire;
if(!isset($proprietaire)) {$proprietaire = new proprietaire;}
?>


<div class="form-group">
    {!! Form::label('nom', 'Nom:', ['class' => "col-sm-2 control-label"]) !!}
    <div class = 'col-sm-10'>
        {!! Form::text('nom', $proprietaire->nom, ['class' => 'form-control']) !!}
        {{ $errors->first('nom') }}
    </div>
</div>

<div class="form-group">
    {!! Form::label('telephone', 'Téléphone:', ['class' => "col-sm-2 control-label"]) !!}
    <div class = 'col-sm-10'>
        {!! Form::text('telephone', $proprietaire->telephone, ['class' => 'form-control']) !!}
        {{ $errors->first('telephone') }}
    </div>
</div>

<div id="animauxSelect" class="form-group">
    {!!Form::label('dummy', "Animaux:", ['class' =>"col-sm-2 control-label"])!!}
    <div class = 'col-sm-7'>
        {{-- Exemple d'un select multiple
            animaux_id[] : la liste d'id selectionnés qui sera retourné
            $animaux : nom et id des animaux à lister (tous les animaux)
            $proprietaire->animaux->lists('id')->all() : les animaux présentement associés à ce proprio (valeur par défaut)
            'id' : la table contenant les id à utiliser
            'size' : le nombre d'entrés à afficher
            'multiple' : si true, alors permet de faire un select multiple
            'class' : classe CSS pour l'affichage.

        --}}
        {{ Form::select('animaux_id[]', $animaux, $proprietaire->animaux->pluck('id') ,
                ['id' => 'animaux_id', 'size' => 5, 'multiple'=> 'true', 'class' => 'form-control']) }}
    </div>
</div>

resources/views/proprietaire/index.blade.php
@extends('layout')
@section('content')

    <div class="container">
        <section class="section-padding">
            <div class="jumbotron text-left">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1> Liste des propriétaires</h1>
                        {{ Form::open(['action'=> ['ProprietairesController@create'], 'role' => 'form', 'method' => 'get', 'class' => 'form-inline']) }}
                            <div class="form-group">
                                <div>
                                    {{ Form::submit('Créer un proprietaire', ['class' => 'btn btn-primary'])}}
                                </div>
                            </div>
                        {{ Form::close() }}
                        @if ($proprietaires->isEmpty())
                            <p> Rien à lister.</p>
                        @else
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nom</th>
                                    <th>Téléphone</th>
                                    <th></th>
                                    <th></th>

                                </tr>
                                </thead>
                                <tbody>
                                @foreach($proprietaires as $proprietaire)
                                    <tr>
                                        <td><a href ="{{ action('ProprietairesController@show', [$proprietaire->id]) }}"> {{ $proprietaire->id }}</a> </td>
                                        <td>{{ $proprietaire->nom }}</td>
                                        <td>{{ $proprietaire->telephone }}</td>
                                        <td><a href="{{ action('ProprietairesController@edit', [$proprietaire->id]) }}" class="btn btn-info">Éditer</a></td>
                                        <td>
                                            {{-- Exemple d'un popup de confirmation avant d'effacer
                                                 Le code JS est dans public/js/script.js, qui est inclue dans layout.blade.php --}}
                                            {{ Form::open(array('action' => array('ProprietairesController@destroy', $proprietaire->id), 'method' => 'delete', 'data-confirm' => 'Êtes-vous certain?')) }}
                                                <button type="submit" href="{{ URL::route('proprietaires.destroy', $proprietaire->id) }}" class="btn btn-danger btn-mini">Effacer</button>
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </section>
    </div>


@stop

resources/views/proprietaire/show.blade.php
@extends('layout')
@section('content')

    <section class="header section-padding">
        <div class="container">
            <div class="header-text">
                <h1>Affichage d'un propriétaire</h1>
            </div>
        </div>
    </section>
    <div class="container">
        <section class="section-padding">
            <div class="jumbotron text-left">
                <div class="form-horizontal">
                    @include('proprietaire.editForm')
                </div>
            </div>

        </section>
    </div>
@stop