routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*
 * ATTENTION à partir de Laravel 8.0, il y a un changement dans le routing qui peut faire que les views ne
 * fonctionnent plus correctement lors de l'appel de "action"
 * voir https://laravel.com/docs/8.x/upgrade#routing
 * Par exemple, cette ligne dans layout.blade.php ne fonctionnera pas si le namespace n'est pas rétablie
 * <a href="{!! action('ProprietairesController@index') !!}">
 */
Route::resource('proprietaires', 'ProprietairesController');
Route::resource('animaux', 'AnimauxController');

app/Models/Animal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Animal extends Model
{
    //Exemple d'un nom de table ne respectant pas la convention (animaux au lieu de animals)
    protected $table = 'animaux';
    protected $guarded = array('id');

    public function proprietaires() {
        //Exemple de spécification du nom de la table ne respectant pas la convention
        //Exemple de spécification du nom de la foreign key ne respectant pas la convention (animal_id au lieu de animaux_id)
        return $this->belongsToMany('App\Models\Proprietaire','animaux_proprietaires', 'animal_id');
    }

    public function espece() {
        return $this->belongsTo('App\Models\Espece');
    }
}

resources/views/animal/create.blade.php
@extends('layout')
@section('content')

    <section class="header section-padding">
        <div class="container">
            <div class="header-text">
                <h1>Création d'un animal</h1>
            </div>
        </div>
    </section>

    <div class="container">
        <section class="section-padding">
            <div class="jumbotron text-left">
                {!! Form::open(['url'=> 'animaux', 'class' => 'form-horizontal', 'role'=>'form']) !!}
                @include('animal.editForm')
                <div class="form-group">
                    {!! Form::submit('Créer', ['class' => 'btn btn-primary'])!!}
                </div>
                {!! Form::close() !!}
            </div>

        </section>
    </div>
@stop

resources/views/animal/edit.blade.php
@extends('layout')
@section('content')

    <section class="header section-padding">
        <div class="container">
            <div class="header-text">
                <h1>Édition d'un animal</h1>
            </div>
        </div>
    </section>

    <div class="container">
        <section class="section-padding">
            <div class="jumbotron text-left">
                {!! Form::open(['action'=> ['AnimauxController@update', $animal->id], 'method' => 'PUT', 'class' => 'form-horizontal', 'role'=>'form']) !!}
                @include('animal.editForm')
                <div class="form-group">
                    {!! Form::submit('Sauvegarder', ['class' => 'btn btn-primary']) !!}
                </div>
                {!! Form::close() !!}
            </div>
        </section>
    </div>
@stop

resources/views/animal/editForm.blade.php
<?php
use App\Models\Animal;

if(!isset($animal)) {
    $animal = new animal;
    $especeId = $especes->keys()->first();
} else {
    $especeId = $animal->espece->id;
}
?>


<div class="form-group">
    {!! Form::label('nom', 'Nom:', ['class' => "col-sm-2 control-label"]) !!}
    <div class = 'col-sm-10'>
        {!! Form::text('nom', $animal->nom, ['class' => 'form-control']) !!}
        {{ $errors->first('nom') }}
    </div>


</div>

<div id="especesSelect" class="form-group">
    {!!Form::label('dummy', "Espece:", ['class' =>"col-sm-2 control-label"])!!}
    <div class = 'col-sm-7'>
        {{ Form::select('espece_id', $especes, $especeId, ['class' => 'form-control']) }}
    </div>
</div>

resources/views/animal/index.blade.php
@extends('layout')
@section('content')

    <div class="container">
        <section class="section-padding">
            <div class="jumbotron text-left">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1> Liste des animaux</h1>
                        {{ Form::open(['action'=> ['AnimauxController@create'], 'role' => 'form', 'method' => 'get', 'class' => 'form-inline']) }}
                            <div class="form-group">
                                <div>
                                    {{ Form::submit('Créer un animal', ['class' => 'btn btn-primary'])}}
                                </div>
                            </div>
                        {{ Form::close() }}
                        @if ($animaux->isEmpty())
                            <p> Rien à lister.</p>
                        @else
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nom</th>
                                    <th></th>
                                    <th></th>

                                </tr>
                                </thead>
                                <tbody>
                                @foreach($animaux as $animal)
                                    <tr>
                                        <td><a href ="{{ action('AnimauxController@show', [$animal->id]) }}"> {{ $animal->id }}</a> </td>
                                        <td>{{ $animal->nom }}</td>
                                        <td>{{ $animal->telephone }}</td>
                                        <td><a href="{{ action('AnimauxController@edit', [$animal->id]) }}" class="btn btn-info">Éditer</a></td>
                                        <td>
                                            {{-- Exemple d'un popup de confirmation avant d'effacer
                                                 Le code JS est dans public/js/script.js, qui est inclue dans layout.blade.php --}}
                                            {{ Form::open(array('action' => array('AnimauxController@destroy', $animal->id), 'method' => 'delete', 'data-confirm' => 'Êtes-vous certain?')) }}
                                                <button type="submit" href="{{ URL::route('animaux.destroy', $animal->id) }}" class="btn btn-danger btn-mini">Effacer</button>
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </section>
    </div>


@stop

resources/views/animal/show.blade.php
@extends('layout')
@section('content')

    <section class="header section-padding">
        <div class="container">
            <div class="header-text">
                <h1>Affichage d'un animal</h1>
            </div>
        </div>
    </section>
    <div class="container">
        <section class="section-padding">
            <div class="jumbotron text-left">
                <div class="form-horizontal">
                    @include('animal.editForm')
                </div>
            </div>

        </section>
    </div>
@stop